# Generated by Django 2.2.7 on 2019-11-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_data', models.CharField(max_length=200)),
                ('ingredients_data', models.CharField(max_length=200)),
            ],
        ),
    ]
