# Generated by Django 2.2.7 on 2019-11-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantryapp', '0004_auto_20191114_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='Quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
