# Generated by Django 2.2.7 on 2019-11-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantryapp', '0006_auto_20191115_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
    ]
