# Generated by Django 2.2.7 on 2019-11-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantryapp', '0009_auto_20191115_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
