# Generated by Django 2.2.7 on 2019-12-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantryapp', '0013_auto_20191125_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
